"""cria jogador, cor, partida e participacao

Revision ID: 7187dc0f4ce1
Revises: 
Create Date: 2026-09-03 08:02:24.218349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7187dc0f4ce1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('codigo', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('jogador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apelido', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apelido')
    )
    op.create_table('partida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('cor_vencedora_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cor_vencedora_id'], ['cor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data')
    )
    op.create_table('participacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=False),
    sa.Column('cor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cor_id'], ['cor.id'], ),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogador.id'], ),
    sa.ForeignKeyConstraint(['partida_id'], ['partida.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partida_id', 'jogador_id', name='uq_um_time_por_jogador')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participacao')
    op.drop_table('partida')
    op.drop_table('jogador')
    op.drop_table('cor')
    # ### end Alembic commands ###
