"""adiciona posicao a participacao

Revision ID: 92e8e7270e8f
Revises: 7187dc0f4ce1
Create Date: 2026-09-03 10:40:50.491674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e8e7270e8f'
down_revision: Union[str, None] = '7187dc0f4ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posicao', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participacao', schema=None) as batch_op:
        batch_op.drop_column('posicao')

    # ### end Alembic commands ###
